export enum AppActionTypes {
    WEBSOCKET_CONNECTION_OPEN = '[App] WEBSOCKET_CONNECTION_OPEN',
    WEBSOCKET_CONNECTION_OPEN_SUCCESS = '[App] WEBSOCKET_CONNECTION_OPEN_SUCCESS',
    WEBSOCKET_CONNECTION_OPEN_ERROR = '[App] WEBSOCKET_CONNECTION_OPEN_ERROR'
}