export enum AppActionTypes {
    OPEN_WEBSOCKET_CONNECTION = '[App] OPEN_WEBSOCKET_CONNECTION',
    OPEN_WEBSOCKET_CONNECTION_SUCCESS = '[App] OPEN_WEBSOCKET_CONNECTION_SUCCESS',
    OPEN_WEBSOCKET_CONNECTION_ERROR = '[App] OPEN_WEBSOCKET_CONNECTION_ERROR'
}