export enum ConversationPreviewActionTypes {
    ADD_BLANK_CONVERSATION_PREVIEW = '[ConversationPreview] ADD_BLANK_CONVERSATION_PREVIEW',
    UPDATE_BLANK_CONVERSATION_PREVIEW = '[ConversationPreview] UPDATE_BLANK_CONVERSATION_PREVIEW',
    LOAD_ALL_CONVERSATION_PREVIEWS = '[ConversationPreview] LOAD_ALL_CONVERSATION_PREVIEWS',
    LOAD_ALL_CONVERSATION_PREVIEWS_SUCCESS = '[ConversationPreview] LOAD_ALL_CONVERSATION_PREVIEWS_SUCCESS',
    LOAD_ALL_CONVERSATION_PREVIEWS_ERROR = '[ConversationPreview] LOAD_ALL_CONVERSATION_PREVIEWS_ERROR',
    RECEIVED_CONVERSATION_PREVIEW = '[ConversationPreview] RECEIVED_CONVERSATION_PREVIEW',
    SET_CURRENTLY_SELECTED_CONVERSATION_PREVIEW = '[ConversationPreview] SET_CURRENTLY_SELECTED_CONVERSATION_PREVIEW'
}