export enum ConversationActionTypes {
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW',
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_SUCCESS = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_SUCCESS',
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_ERROR = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_ERROR'
}