export enum ConversationActionTypes {
    CREATE_NEW_CONVERSATION = '[Conversation] CREATE_NEW_CONVERSATION',
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW',
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_SUCCESS = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_SUCCESS',
    LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_ERROR = '[Conversation] LOAD_CONVERSATION_BY_CONVERSATION_PREVIEW_ERROR'
}