export enum ThreadsActionTypes {
    LOAD_ALL_THREADS = '[Threads] LOAD_ALL_THREADS',
    LOAD_ALL_THREADS_SUCCESS = '[Threads] LOAD_ALL_THREADS_SUCCESS',
    LOAD_ALL_THREADS_ERROR = '[Threads] LOAD_ALL_THREADS_ERROR',
    RECEIVED_THREAD_MESSAGE = '[Threads] RECEIVED_THREAD_MESSAGE', // TODO rename Thread to Snippet or Preview
    SET_CURRENTLY_SELECTED_THREAD = '[Threads] SET_CURRENTLY_SELECTED_THREAD'
}