export enum ThreadsActionTypes {
    LOAD_ALL_THREADS = '[Threads] LOAD_ALL_THREADS',
    LOAD_ALL_THREADS_SUCCESS = '[Threads] LOAD_ALL_THREADS_SUCCESS',
    LOAD_ALL_THREADS_ERROR = '[Threads] LOAD_ALL_THREADS_ERROR'
}