export enum UserActionTypes {
    SIGN_IN = '[User] SIGN_IN',
    SIGN_IN_SUCCESS = '[User] SIGN_IN_SUCCESS',
    SIGN_IN_ERROR = '[User] SIGN_IN_ERROR',
    ATTEMPT_AUTH = '[User] ATTEMPT_AUTH',
    ATTEMPT_AUTH_SUCCESS = '[User] ATTEMPT_AUTH_SUCCESS',
    ATTEMPT_AUTH_ERROR = '[User] ATTEMPT_AUTH_ERROR'
}